### ISSUE TITLE
Update checker should notify players with permission on join

### ISSUE THREAD

**Issue by stumper66** [lokka30/LevelledMobs#155]
Submitted by Leasoncre#7439

> when i login, several plugins report to my OP player about updates and relevent info
wondering if that was worth a notice (toggle in config if it really bothers folks)
not sure i'd see it in console. ALOT of new owners don't realize that console iis not infinate, so alot of the startup logs live

**Comment by lokka30** [comment]
* Allow the update checker messages to be configurable. This is possible since it runs *after* the configuration files are loaded anyways. Update checker messages should have multi-line and color support.
* Add permission: `levelledmobs.receive-update-notifications`
* Add to `LevelledMobs` class: `String updateCheckerResult = null`
* When the update checker runs, it will set `updateCheckerResult` to 'a new update is available, latest version ... etc' if an update was found. If no update was found then it will remain null.
* Create/edit class `PlayerJoinListener`. If player has permission above and `updateCheckerResult != null`, then send them a colorized version of `updateCheckerResult`.

**Comment by lokka30** [comment]
Done! Needs testing. Will push the commit in a moment

**Comment by lokka30** [comment]
Tested the following, working great.
- chat message shown to players with permission
- console message shown

A gap in my testing - haven't checked if it breaks when there is no update detected - although I believe this is unlikely. Closing the issue, feel free to re-open
