### ISSUE TITLE
Packet nametags can't be removed

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#171]
**EDIT** See https://github.com/lokka30/LevelledMobs/issues/171#issuecomment-791863608

Unsure what the issue is myself, found it commented out and with a 'TODO' saying 'fix this'.
`LevelledMobs#511`

**Comment by lokka30** [comment]
@stumper66, what is wrong with the Entity Tame Listener? Is it something I can work on?

**Comment by stumper66** [comment]
It was discovered that taming a levelled animal resets it's level.  I was attempting to fix this with the entity tame listener but I was hitting a wall.  It's been a few weeks since I worked on this so I can't remember what exactly the issue was but I do remember I couldn't solve the issue at the time.

Please do work on it if you like.

**Comment by lokka30** [comment]
> It was discovered that taming a levelled animal resets it's level. I was attempting to fix this with the entity tame listener but I was hitting a wall. It's been a few weeks since I worked on this so I can't remember what exactly the issue was but I do remember I couldn't solve the issue at the time.
> 
> Please do work on it if you like.

Thanks for the clarification, this should be enough to get my up and running on solving the issue on the weekend.

**Comment by lokka30** [comment]
Seems to be working completely fine on my end?

**Comment by lokka30** [comment]
Issue found: packet nametags can't be removed
