### ISSUE TITLE
Flooding error in task 724 in console

### ISSUE THREAD

**Issue by MrMineToons** [lokka30/LevelledMobs#222]
**Describe the bug**
So, its flooding erros in the console, on the task 724. Nothing special doing in the server, players are not trying to do it propositally... I dont have much to say about it, but if I can help with any other thing I will be glad to help!!!

**Steps to Reproduce**
1. There is no real steps....

**Expected behavior**
No erros....

**Screenshots**
![image](https://user-images.githubusercontent.com/68707610/118346419-2715b800-b509-11eb-81c6-7d0769351b98.png)

**Server software**
Paper
This server is running Paper version git-Paper-670 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Server version**
Minecraft 1.16.5

**LevelledMobs version**
[23:09:03 INFO]: LevelledMobs version 2.5.3 b393
[23:09:03 INFO]: The Ultimate RPG Mob Levelling Plugin
[23:09:03 INFO]: Website: https://github.com/lokka30/LevelledMobs/wiki
[23:09:03 INFO]: Author: lokka30

**Config files, if applicable**
Please insert a link of each configuration file that may be applicable to the issue. Use [paste.gg](https://paste.gg/) please.
https://paste.gg/p/anonymous/76af410c68ad44bf94d6950937ab52fa

**Additional context**
latest.log: https://paste.gg/p/anonymous/fb7285a153924505bd39981dadc342f0

Thanks in Advance!!! <3

**Comment by lokka30** [comment]
Thank you very much for the report! I have instantly identified the bug thanks to your console log screenshot - the error is that LM is trying to check the distance between two locations, but the two locations have different worlds (this is due to players teleporting whilst LM is calculating it). This process is done for determining nearby mobs to update the nametags of for each player.
It will be an easy fix. I have just wiped my Windows so I will set my programming software back up and fix it now.

**Comment by lokka30** [comment]
Issue closed in latest release 2.5.4
