### ISSUE TITLE
Add MythicMobs Level Matching

### ISSUE THREAD

**Issue by stumper66** [lokka30/LevelledMobs#256]
Requested by MidnightSugar#2177

This is how to level vanilla mobs using mythic mobs:
- For every vanilla mob you want leveled, create a skill using the setLevel() mechanic
- Calculate the distance from spawn, using placeholders from the mobs location and the spawn location and put it into the created setLevel mechanic.
- Create a nametag that has level placeholder, and set it so it updates every few ticks.
- Repeat for every mob

**Comment by MidnightSugar** [comment]
The syncing of mythic mobs levels request is supposed to go from LM to MM, not MM to LM. So, when a mythic mob spawns, LM will do its normal operations to generate its level, then after that is all done, it will assign the level to MM. Since MM closed its API, this may be too difficult or not possible to do, so it may be necessary to wait until its API is public again.

**Comment by lokka30** [comment]
This requires us to use the MM API which they have made very frustrating for every developer to use simply because of the way they are distributing it. No chance this will be added until they have a suitable distribution method for their API. What was used historically worked great.

**Comment by lokka30** [comment]
Unfortunately I must refuse this suggestion, regardless that I would love for it to be added - MM's API is just too unstable.

 MythicMobs are free to add an integration on their end to match with our levels, as LM 4 will have a simple, concrete stable API.
