### ISSUE TITLE
Bug: health indicator color tiers do not translate in custom rules.

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#258]
See https://discord.com/channels/752310043214479462/757933745620779033/869880453174280254

**Comment by UltimaOath** [comment]
I believe the 'bigger picture' of this issue is that not all presets set in defaults interact with presets set in custom rules. Sometimes there's straight conflict, sometimes the issue will visually switch between options when `chance:` is invoked (for example, I would have a preset set in defaults and a similar but different preset set in a custom rule, and entities spawned with the custom rule will often have a mixture of the possible outputs occurring repeatedly (visual changes) or splitting two presets (for example, setting special attributes on an entity as a custom rule, and that entity spawning under default rule settings except for one or two seemingly randomly selected attributes modified; or a custom rule entity would spawn 95% correct with one or two factors matching the default rule. I think the visual stuff are linked to whatever checks for entity or nametag updates, as the visuals occur more frequently while an entity is taking damage repeatedly (example: sunlight damage). I believe this is some sort of caching issue where bits and pieces are being left behind from prior rule applications and not being fully cleared and restacked as necessary. My lack of javanese limits my ability to speak in code but I can describe what I'm seeing :X

**Comment by UltimaOath** [comment]
Fixed in b482
