### ISSUE TITLE
Mob skill implementation (custom actions)

### ISSUE THREAD

**Issue by jwevans1989** [lokka30/LevelledMobs#304]
Right now, the `customdrops.yml` custom command feature allows any command to be executed when a mob is killed. This can be used to implement, to a degree, a rudimentary skill system without having to add anything extra to the plugin. For example, a witch might have the chance to heal a player upon death, or summon a huge explosion that can kill anyone who is too close.

However, in terms of mobs actually using skills, there is nothing yet in place.

**Solution**
Add custom actions (`customactions.yml`?) to mobs that trigger/have a chance to trigger custom commands (skills, vanilla commands, etc.) whenever they perform a specific action. For example:
- Melee hostile mobs (zombies, iron golems, etc.) may trigger a "Stun*" skill when they hit the player.
- Passive mobs (chickens, cows, etc.) may drop feathers, leather, etc. every time they are hit by the player, or damaged by the environment.
- Ranged hostile mobs (skeletons, ghasts, etc.) may trigger a "Blight Aura*" skill that functions the same as the Ender Dragon's dragon breath.

_* made up skills for the sake of illustration_

**Comment by UltimaOath** [comment]
[https://github.com/lokka30/LevelledMobs/issues/317#issuecomment-962585260](https://github.com/lokka30/LevelledMobs/issues/317#issuecomment-962585260)

I wrote an expansion to the 'Soft Custom-Entity Reconstruction' system called the 'Entity Combat Tree (ECT)'. This ECT would be able to do what this issue requires so will close this to focus on that unless someone feels otherwise :)
