### ISSUE TITLE
Adding a distance mechanic to TARGETED nametag visibility

### ISSUE THREAD

**Issue by stumper66** [lokka30/LevelledMobs#327]
suggested by Zer0#7111

If possible add a configurable range values to nametag visibility system.
Perhaps would be applicable to TARGETED, TRACKING and ATTACKED.  If that's not possible or doesn't make sense then just the TARGETED value.

**Comment by UltimaOath** [comment]
`TARGETED` - Should work as expected; line of sight limited.  
`ATTACKED` - Could work for projectiles, but melee requires close distance anyway.  
`TRACKING` - Within follow range mechanics, so would need to be close; potentially could work but doubtful it'd be useful.  
`ALWAYS_ON` - Should work as expected; always on within distance even through blocks.  
`MELEE` - Prob won't work since melee is close.  
`DISABLED` - Disabled anway.

**Comment by lokka30** [comment]
Should we create a new issue that unifies the nametag visibility mode suggestions? @stumper66 @UltimaOath

**Comment by lokka30** [comment]
Added to brainstorming actions file.
