### ISSUE TITLE
WorldGuard level limits might not be working

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#87]
Reported by Rexsan
Needs testing to confirm that this is actually a bug.

**Comment by stumper66** [comment]
I can confirm WorldGuard mostly works as expected.  With version 1.34 I created a region and set min flag to 5 and max to 6 and it only spawned mobs of level and 5 and 6 within the region.
However there is a bug where if you put the same value for min and max, the max value will be ignored.  This has been fixed in the upcoming 1.4 release.

If you still think the WG regions are not being respected, verify the region has the highest priority if there are multiple and that the mobs are not coming in from somewhere outside the region.
